chef/urls.py
from django.contrib import admin
from django.urls import path, include
from chef import views

app_name = 'chef'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chef/', views.chef, name='chef'),
    path('chef/done/<int:id>/', views.chef_done, name='chef_done'),
    path('chef/request/', views.bahan, name='bahan'),
  ]

groupProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('chef.urls')),
    path('', include('homepagee.urls')),
    path('', include('kurir.urls'))
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('order/', views.person_create, name="person"),
]

homepagee/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'homepagee'

urlpatterns = [
    path('show/', views.post_list, name='post_list'),
    
    path('bayar/', views.post_new, name='bayar'),
    path('feedback/', views.feedback, name='feedback'),
    
    url(r'show/(?P<pk>[0-9]+)/delete/$', views.Delete.as_view(),name='delete'),
]

kurir/urls.py
from django.contrib import admin
from django.urls import path, include
from kurir import views

app_name = 'kurir'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kurir/', views.chef, name='kurir'),
  ]

chef/models.py
from django.db import models

# Create your models here.
class Bahan(models.Model):
	nama = models.CharField(max_length = 50)
	form = models.TextField(blank = True, null = True)
		
		 

homepage/models.py
from django.db import models
import django.utils.timezone


# Create your models here.
class Person1(models.Model):

    name = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
   
    date = models.DateField(auto_now_add = False, default = django.utils.timezone.now)

    BASE = [
        ('Choco', 'Choco'),
        ('Mix', 'Mix'),
        ('Original', 'Original')
    ]

    donut_base = models.CharField(choices=BASE, default='Original', max_length=10)

    donut_flav_A = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_B = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_C = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_D = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_E = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_F = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_G = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_H = models.DecimalField(default=0, max_digits=2, decimal_places=0)

    def __str__(self):
        return self.name

    def deftanggal(self):
        return self.date.strftime('%d')
        
    def bulan(self):
        return self.date.strftime('%b')
# class Person1(models.Model):

    # name = models.CharField(max_length=100)
    # number = models.DecimalField(max_digits=100, decimal_places=0)
    # address = models.CharField(max_length=100)
   
    # date = models.DateField(auto_now_add = False, default = django.utils.timezone.now)
    # day = models.CharField(max_length=10, default=None, null=True)
    # time = models.TimeField(auto_now_add = False, default = django.utils.timezone.now)

    # BASE = [
    #     ('Choco', 'Choco'),
    #     ('Mix', 'Mix'),
    #     ('Original', 'Original')
    # ]

    # donut_base = models.CharField(choices=BASE, default='Original', max_length=10)
    
    # donut_flav_A = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_B = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_C = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_D = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_E = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_F = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_G = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_H = models.DecimalField(max_digits=2, decimal_places=0)

    # def __str__(self):
    #     return self.title

homepagee/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    nama=models.CharField(max_length=30, default="")
    feedback= models.CharField(max_length=200)
    
    
    

    def __str__(self):
        return self.nama
        
   

kurir/models.py
from django.db import models

# Create your models here.

chef/forms.py
from django import forms
from . import models

class RequestBahan(forms.ModelForm):
	class Meta:
		model = models.Bahan
		fields = ['nama', 'form']
			


	

homepage/forms.py
from django import forms
from . import models
from django.utils import timezone
from datetime import datetime

class Time(forms.TimeInput):
    input_type = "time"

class Date(forms.DateInput):
    input_type = "date"
    input_formats = ['%d %b %Y']

class Person(forms.ModelForm):
    class Meta:
        model = models.Person1
        fields = ['name', 'number', 'address', 'date', 'donut_base', 'donut_flav_A', 'donut_flav_B', 'donut_flav_C', 'donut_flav_D', 'donut_flav_E', 'donut_flav_F', 'donut_flav_G', 'donut_flav_H']

        widgets = {
            "date": Date
        }

homepagee/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['nama', 'feedback']
        
        
        
    def __init__(self, *args, **kwargs):
        super(PostForm,self).__init__(*args,**kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        

chef/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from homepage.models import Person1
from .models import Bahan
from . import forms
# Create your views here.

def chef(request):
	response = {}
	pesanan1 = Person1.objects.all().order_by('date')
	response['pesanan_list'] = pesanan1
	return render(request, "chef.html", response)

def chef_done(request, id):
	if request.method == 'POST':
	    Person1.objects.filter(id=id).delete()
	    return redirect('chef:chef')
	else:
	    return HttpResponse("/GET not allowed")

def bahan(request):
	if request.method == 'POST':
		form = forms.RequestBahan(request.POST, request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			form.save()
			return redirect('chef:chef')
	else:
		form = forms.RequestBahan()
	return render(request, 'request_bahan.html', {'form' : form})

homepage/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Person1

# Create your views here.
def home(request):
    return render(request, "home.html")

def person_create(request):
    if request.method == "POST":
        form = forms.Person(request.POST)

        if form.is_valid():   
            new_sched = form.save(commit=False)
            new_sched.save()
            return redirect('homepagee:post_list')
    else:
        form = forms.Person()

    return render(request, "schedule.html", {"form" : form, "person": Person1.objects.all().order_by("date")})

homepagee/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from homepage.models import Person1
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from homepagee.forms import PostForm
from homepagee.models import Post
# Create your views here.
def post_list(request):
    return render(request, 'post_list.html', {'postlist': Person1.objects.all()})
    
def feedback(request):
    postlist = Post.objects.all()
    return render(request, 'feedback.html', {'postlist2':postlist})
    
    
def post_new(request):
    if request.method == "POST":
           form = PostForm(request.POST)
           if form.is_valid():
               post = form.save()
               post.save()
               return redirect('/feedback/')
    else:
        form = PostForm()
    return render(request, 'bayar.html', {'form': form})
    
    
class Delete(DeleteView):
    model=Person1
    success_url=reverse_lazy('homepagee:post_list')
    

kurir/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from homepage.models import Person1
# Create your views here.

def chef(request):
	response = {}
	pesanan = Person1.objects.all().order_by('date')
	print(pesanan)
	response['pesanan_list'] = pesanan
	return render(request, "kurir.html", response)

chef/templates/chef.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel = "stylesheet" href = "{% static 'css/chef_style.css' %}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>King Donat</title>
</head>

<body id="chef">
		<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F8BBD0;">
				<a class="navbar-brand" href="{% url 'homepage:home' %}">Donat</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavDropdown">
				  <ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:home' %}">Beranda</a>
					</li>
					<li class="nav-item">
							<a class="nav-link" href="{% url 'homepage:person' %}">Pesan</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'chef:chef' %}">Koki</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'kurir:kurir' %}">Kurir</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
					</li>
				  </ul>
				</div>
			</nav>
	<div class="container">
		<diccv class= "row">
		{% for news in pesanan_list %}
			<div class="col-2">
				<h3>{{news.name}}</h3>
					<p>{{news.donut_base}}</p>
			          	<ul>
						  	{% if news.donut_flav_A != 0 %}
							 	<li><p> Donat A : {{news.donut_flav_A}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_B != 0 %}
							 	<li><p>Donat B : {{news.donut_flav_B}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_C != 0 %}
							 	<li><p>Donat C : {{news.donut_flav_C}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_D != 0 %}
							 	<li><p>Donat D : {{news.donut_flav_D}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_E != 0 %}
							 	<li><p>Donat E : {{news.donut_flav_E}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_F != 0 %}
							 	<li><p>Donat F : {{news.donut_flav_F}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_G != 0 %}
							 	<li><p>Donat G : {{news.donut_flav_G}} pcs</p></li>
							{% endif %}

							{% if news.donut_flav_H != 0 %}
							 	<li><p>Donat H : {{news.donut_flav_H}} pcs</p></li>
							{% endif %}
						</ul>

					<div class = 'form-group'>
                      <form action="done/{{ news.id }}/" method="POST">
                          {% csrf_token %}
                          <button class="btn btn-danger" type="submit">Done</button>
                      </form>	
                    </div>
			</div>
		{% endfor %}
	</div>
	<div class="row justify-content-center">
	<a href="{% url 'chef:bahan' %}"><button class="btn" style= "background-color: #FBE2BD">Request</button></a>
	</div>
</body>
</html>

chef/templates/request_bahan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel = "stylesheet" type="text/css" href ="{% static 'css/chef_style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>King Donat</title>
</head>

<body id="req">

	<div class="row justify-content-center formBahan ">
		<form class="formreq" action="" method="post">
			<div>
		        {% csrf_token %}
		        <div class="form-row">
	        		<div class="form-group col-sm-10">
	        			<br>
	        			<p> 
	        			<br>
	        				Nama Koki :
	        			<br>
		                    {{ form.nama }}
		                </p>
		                <p>
		                <br>
						Bahan :
		                    {{ form.form }}
		                </p>
	                	</div>
            	</div>
		    </div>
			<input type="submit" value="submit" style="background-color: #D8AEAE">    
	    </form>
	    <div class="row justify-content-right" style="width: 100px; height: auto;">
        	<img src="{% static 'img/donat.png' %}" alt="donat"> 
    	</div>
	</div>
</body>

</html>

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw2.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F8BBD0;">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Donat</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Beranda</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:person' %}">Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chef:chef' %}">Koki</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'kurir:kurir' %}">Kurir</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>

          </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

homepagee/templates/feedback.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<html>
<head>
	<title>Ringkasan</title>
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" >
	
	
	
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
	<style>
		.btq{
			background:#FFAAA5;
		}
		.bg{
			background-color:#F5AB40;
		}
		.a{
			color:#FF8B20;
			text-align:center;
		}
		.post{
			display: flex;
			justify-content: center;
			align-items: center;
		}

		.row-striped:nth-of-type(odd){
		  background-color: #FFAAA5;
		  border-left: 4px #000000 solid;
		}

		.row-striped:nth-of-type(even){
		  background-color: #F3A67B;
		  border-left: 4px #efefef solid;
		}

		.row-striped {
		    padding: 15px;
		}
		.k{
			margin:3px;
		}
		</style>
		<div class="k">
	<a href="{% url 'homepage:home' %}"><img src="{% static 'lg.png' %}" width="100px"></a>
</div>
	<br><br>
	<h1 class="a"> Feedback </h1>
	
	<div class="show post container">
		<div class= "col-xl-6">
		<br><br><br><br>
		{% for post in postlist2 %}
			<div class="row row-striped">
				<p><strong>{{ post.nama}}</strong><br>
				{{post.feedback}} </p>
				
					</div>				
				
					{% endfor %}
					<div clas= "a"><p ><br><br>Terimakasih atas feedbacknya, kembali ke <a href={% url 'homepage:home'%}>home</a></p></div>
		<br><br>
	</div>
		
			
					
					
				
			   	


</html>

homepagee/templates/post_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<html>
<head>
	<title>Ringkasan</title>
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" >
	
	
	
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
	<style>
		.btq{
			background:#FFAAA5;
		}
		.bg{
			background-color:#F5AB40;
		}
		.a{
			color:#FF8B20;
			text-align:center;
		}
		.space{
			margin:5%;
		}
		.post{
			display: flex;
			justify-content: center;
			align-items: center;
		}

		.row-striped:nth-of-type(odd){
		  background-color: #FFAAA5;
		  border-left: 4px #000000 solid;
		}

		.row-striped:nth-of-type(even){
		  background-color: #F3A67B;
		  border-left: 4px #efefef solid;
		}

		.row-striped {
		    padding: 15px 0;
		}
		.gambar1{
			width:300px;
		}
		#nol{
			padding:0px;
			margin:0px;
		}
		#hitam{
			color:black;
		}
		.dikit{
			margin:10%;
		}
		.left{
			margin-left:15%;
		}
		.k{
			margin:3px;
		}
		</style>
		<div class="k">
	<img src="{% static 'lg.png' %}" width="100px">
</div>
	
	<h1 class="a"> Ringkasan order </h1>
	<br>
	
	<div class="show post container">
		<div class= "col-xl-8">
		<br>
		{% for post in postlist %}
			<div class="row row-striped">
				<div class="container">
				<div class="row">
						<div class="col-2 text-right">
							<h1 class="display-4"><span class="badge badge-secondary">{{ post.deftanggal }}</span></h1>
							<h2>{{ post.bulan }}</h2>
						</div>
						<div class="col">
							<div class="text-uppercase"><strong>{{ post.name }}</strong></div>
							<p>{{ post.number }}</p>
							<p>{{ post.address }}</p>
							
							
						</div>
						<div class="col" id="nol">
							{% if post.donut_flav_A != 0 %}
								<p> Donat A : {{post.donut_flav_A}} pcs</p>
							{% endif %}

							{% if post.donut_flav_B != 0 %}
								<p> Donat B : {{post.donut_flav_B}} pcs</p>
							{% endif %}

							   {% if post.donut_flav_C != 0 %}
								<p> Donat C : {{post.donut_flav_C}} pcs</p>
							{% endif %}
							
							{% if post.donut_flav_D != 0 %}
								<p> Donat D : {{post.donut_flav_D}} pcs</p>
							{% endif %}

							{% if post.donut_flav_E != 0 %}
								<p> Donat E : {{post.donut_flav_E}} pcs</p>
							{% endif %}

							{% if post.donut_flav_F != 0 %}
								<p> Donat F : {{post.donut_flav_F}} pcs</p>
							{% endif %}

							{% if post.donut_flav_G != 0 %}
								<p> Donat G : {{post.donut_flav_G}} pcs</p>
							{% endif %}

							{% if post.donut_flav_H != 0 %}
								<p> Donat H : {{post.donut_flav_H}} pcs</p>
							{% endif %}

						</div>
					</div>
				</div>
					</div>
					<form action="{% url 'homepagee:delete' post.id %}" method="post">
						{% csrf_token %}
					    <input type="hidden" name="post_id" value="{{ post.id }}"/>
					        <button type="" id="hitam" class="btn btn-outline-warning " style="margin-left: 30%;" >
							
					         Hapus
					        </button> 
					</form>
				
					{% endfor %}
					</div>
				</div>
		<br>
					  <div class="dikit">
					    <div class="row">
					      <div class="col-sm-4 left">
					        <img src="{% static 'd.png' %}"  class="gambar1">
					      </div>
					      <div class="col-sm-4">
							<div clas="dikit">
												   	    <div class="row">
			   	      
												   	      <div class="col bg">
												   	        <br><br><h3> <span class="label label-default h3 ">Apakah orderan anda sudah benar?<br><br>
									<div class="container">
									  <div class="row">
									    <div class="col">
									      <a href="{% url 'homepagee:bayar' %}"><button type="button" class="btn btn-outline-secondary btq" >Yes</button>
									    </div>
									    <div class="col">
									      <a href="{% url 'homepage:person' %}"><button type="button" class="btn btn-outline-secondary btq"bg>No</button></a>
									    </div>
									  </div>
								  </span></h3><br>
							  </div>
							</div>
							</div>
							</div>
    
	
							</div>
					      </div>
					    </div> 	
						
	
		
			
					
					
				
			   	

</body>
{% load staticfiles %}
</html>

kurir/templates/kurir.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw1.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>King Order</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F8BBD0;">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Donat</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Beranda</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:person' %}">Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chef:chef' %}">Koki</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'kurir:kurir' %}">Kurir</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
          </ul>
        </div>
    </nav>
    <div class="container package-section">
        <div class= "row mt-5">
        {% for news in pesanan_list %}
            <div class="col-md-3 offset-md-1 text-center bg-warning mt-5">
                <h3>{{news.name}}</h3>    
                <p>{{news.number}}</p>
                <p>{{news.address}}</p>

                <div class = 'form-group'>
                    <form action="{{ news.id }}/" method="POST">
                        {% csrf_token %}   
                    </form>   
                </div>
            </div>
        {% endfor %}
    </div>

    </div>
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
</body>

</html>